// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GF_Shop/internal/dao/internal"
)

// internalAddressInfoDao is an internal type for wrapping the internal DAO implementation.
type internalAddressInfoDao = *internal.AddressInfoDao

// addressInfoDao is the data access object for the table address_info.
// You can define custom methods on it to extend its functionality as needed.
type addressInfoDao struct {
	internalAddressInfoDao
}

var (
	// AddressInfo is a globally accessible object for table address_info operations.
	AddressInfo = addressInfoDao{
		internal.NewAddressInfoDao(),
	}
)

// Add your custom methods and functionality below.
