// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GF_Shop/internal/dao/internal"
)

// internalCartInfoDao is an internal type for wrapping the internal DAO implementation.
type internalCartInfoDao = *internal.CartInfoDao

// cartInfoDao is the data access object for the table cart_info.
// You can define custom methods on it to extend its functionality as needed.
type cartInfoDao struct {
	internalCartInfoDao
}

var (
	// CartInfo is a globally accessible object for table cart_info operations.
	CartInfo = cartInfoDao{
		internal.NewCartInfoDao(),
	}
)

// Add your custom methods and functionality below.
