// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GF_Shop/internal/dao/internal"
)

// internalGoodsInfoDao is an internal type for wrapping the internal DAO implementation.
type internalGoodsInfoDao = *internal.GoodsInfoDao

// goodsInfoDao is the data access object for the table goods_info.
// You can define custom methods on it to extend its functionality as needed.
type goodsInfoDao struct {
	internalGoodsInfoDao
}

var (
	// GoodsInfo is a globally accessible object for table goods_info operations.
	GoodsInfo = goodsInfoDao{
		internal.NewGoodsInfoDao(),
	}
)

// Add your custom methods and functionality below.
