// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GF_Shop/internal/dao/internal"
)

// internalOrderInfoDao is an internal type for wrapping the internal DAO implementation.
type internalOrderInfoDao = *internal.OrderInfoDao

// orderInfoDao is the data access object for the table order_info.
// You can define custom methods on it to extend its functionality as needed.
type orderInfoDao struct {
	internalOrderInfoDao
}

var (
	// OrderInfo is a globally accessible object for table order_info operations.
	OrderInfo = orderInfoDao{
		internal.NewOrderInfoDao(),
	}
)

// Add your custom methods and functionality below.
